export let peliculasDB=[
	{
		nombre:'Rayo MCweed',
		nombreOriginal:'Thunder MCweed',
		clasificacion:'+18',
		duracion:'2:00:00',
		descripcion:'Es la historia de un auto el cual de joven empieza en el consumo de los alucinogenos y resulta ser el primer atuo volodar que vuela, en una pelicula de accion, drama y cosas fuera de lo comun',
		genero:['+18',
			    'Accion',
			    'Drama'],
		puntaje:'10',
		director:'Angel Tobon Perez',
		actores:'Carlos Arturo Henriquez, Angel Tobon Perez, Maria Eugenia 	Tirimisu',
		fechaDeLanzamiento:'17-09-2020',
		pais:'Colombia',
		calidadVisual:'HD',
		video:'https://www.youtube.com/watch?v=lXLPVQ-WrU4',
		foto:'../../assets/img/flor-de-epcot-y-el-festival-de-jardin-2019-rayo-mcqueen-topiary-s2w506.jpg'
		
	},
	{
		nombre:'Dragon Ball Super: Super Hero',
		nombreOriginal:'Dragon Ball Super: Super Hero',
		clasificacion:'+8',
		duracion:'3:00:00',
		descripcion:'Son Goku destruyó en su momento al Ejército Red Ribbon. Ahora, ciertos individuos han decidido continuar con su legado y han creado a los androides definitivos: Gamma 1 y Gamma 2. Estos dos androides se autoproclaman "superhéroes" y deciden atacar a Piccolo y a Gohan. ¿Cuál es el objetivo del Nuevo Ejército Red Ribbon? Ante un peligro inminente, ¡llega el momento del despertar del Superhéroe!',
		genero:['Animacion',
			    'Ciencia Ficcion',
			    'Accion'],
		puntaje:'6',
		director:'Akira Toriyama',
		actores:'Masako Nozawa, Toshio Furukawa, Yuko Minaguchi, Hiroshi Kamiya, Mamoru Miyano, Miyu Irino, Ryota Takeuchi, Aya Hisakawa, Mayumi Tanaka, Ryou Horikawa',
		fechaDeLanzamiento:'17-09-2022',
		pais:'Japan',
		calidadVisual:'HD',
		video:'https://www.youtube.com/embed/lXLPVQ-WrU4',
		foto:'../../assets/img/dragonball.jpg'
	},
	{
		nombre:'El conjuro 2',
		nombreOriginal:'The conjuring 2',
		clasificacion:'+16',
		duracion:'2:14:00',
		descripcion:'Secuela de la exitosa Expediente Warren (2013), que lleva de nuevo a la pantalla otro caso real de los expedientes de los renombrados demonólogos Ed y Lorraine Warren. En este caso ambos viajarán al norte de Londres para ayudar a una madre soltera que tiene a su cargo cuatro hijos y que vive sola con ellos en una casa plagada de espíritus malignos.',
		genero:['Terror',
				'Suspenso'],
		puntaje:'8',
		director:'Don Burgues',
		actores:' Patrick Wilson, Vera Farmiga, Madison Wolfe, Frances OConnor, Simon McBurney, Lauren Esposito, Benjamin Haigh, Sterling Jerins, Maria Doyle Kennedy, Patrick McAuley',
		fechaDeLanzamiento:'13-05-2016',
		pais:'United States of America',
		calidadVisual:'720p',
		video:'https://www.youtube.com/embed/cuDBjj_Gs0M',
		foto:'../../assets/img/ELconjuro2'
		
	},
	{
		nombre:'Spider-Man:Sin Camino a Casa',
		nombreOriginal:'Spider-Man:No Way Home',
		clasificacion:'+12',
		duracion:'1:00:00',
		descripcion:'Peter Parker es desenmascarado y por tanto no es capaz de separar su vida normal de los enormes riesgos que conlleva ser un súper héroe. Cuando pide ayuda a Doctor Strange, los riesgos pasan a ser aún más peligrosos, obligándole a descubrir lo que realmente significa ser Spider-Man.',
		genero:['Aventura',
				'Accion',
				'Ciencia Ficcion'],
		puntaje:'9',
		director:'Sanja Milkovic Hays',
		actores:'Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon, Jon Favreau, Jamie Foxx, Willem Dafoe, Alfred Molina, Benedict Wong, Tony Revolori',
		fechaDeLanzamiento:'17-04-2021',
		pais:'United States of America',
		calidadVisual:'HD',
		video:'https://www.youtube.com/embed/r6t0czGbuGI',
		foto:'../../assets/img/spiderman.jpg'
		
	},

]